# Generated by Django 3.1.5 on 2021-02-03 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catteries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'sale'), (1, 'knitting')])),
                ('level', models.IntegerField(choices=[(0, 'sale'), (1, 'knitting')], default=0)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('deletionDate', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generalAdvertisements', to='catteries.breed')),
                ('cats', models.ManyToManyField(blank=True, to='catteries.Breed')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generalAdvertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(upload_to='advertisement_attachments')),
                ('cattery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisementAttachments', to='catteries.cattery')),
            ],
        ),
        migrations.CreateModel(
            name='CatteryAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'sale'), (1, 'knitting')])),
                ('level', models.IntegerField(choices=[(0, 'sale'), (1, 'knitting')], default=0)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('deletionDate', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('creationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catteryAdvertisements', to='catteries.breed')),
                ('cats', models.ManyToManyField(blank=True, to='catteries.Breed')),
                ('cattery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='catteries.cattery')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catteryAdvertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
